#! /bin/bash

rm -fv dot.bashrc-lfs
rm -fv lfs-05-build-as-lfs
find src -mindepth 1 -maxdepth 1 -type d -exec rm -rfv {} \;

rm -fv BLFS-ca-bundle*.crt
rm -fv *-jail
rm -fv certdata.txt
rm -fv lfs.out
rm -fv src/wl
rm -fv tmpl
rm -rfv blfs-bootscripts-*
