#! /bin/bash

CURRENT_TS=$(date '+%Y%m%d_%H%M%S')

set +e
mount | grep /mnt/host
if [ 0 -ne $? ] ; then
	echo "Doesn't look like /mnt/host is mounted; try again."
	exit
fi
set -e

echo "* Installing new kernel and hypervisor..."
cd /boot
for file in \
  config-3.1 \
  System.map-3.1 \
  vmlinuz-3.1-lfs-7.0 \
  xen-4.1.2.gz \
  xen-syms-4.1.2
do
	if [ -f $file ] ; then
		/bin/cp -vf $file /mnt/host/boot/$file-$CURRENT_TS
		/bin/cp -vf $file /mnt/host/boot
	fi
done

echo
echo "  DONE -- Make sure the GRUB boot files are adjusted before rebooting!"
echo
