#! /bin/bash

set +e
mount | grep /mnt/host
if [ 0 -ne $? ] ; then
	echo "Doesn't look like /mnt/host is mounted; try again."
	exit
fi
set -e

echo "* Installing new kernel and hypervisor..."
cd /boot
for file in *
do
	if [ -f $file ] ; then
		/bin/cp -vf $file /mnt/host/boot
	fi
done

echo
echo "  DONE -- Make sure the GRUB boot files are adjusted before rebooting!"
echo
