#! /bin/bash

set +h
umask 022
PATH=/bin:/usr/bin:/sbin:/usr/sbin
export PATH

export LFS="/"

cd /lfs
find src -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;
chmod a+rw src
pwd
./build-all -s b2.01 -e b2.20

