#! /bin/bash

JUST_TESTING=$1
if [ -z "$JUST_TESTING" ] ; then JUST_TESTING=0 ; fi

set -e
set +h

echo "################################################################"
echo "#"
echo "# -----=====>>>>> LFS ENVIRONMENT PREPARED <<<<<=====-----"
echo "#"
echo "################################################################"

pushd /home/lfs
su lfs -c "./lfs-05-build-as-lfs $JUST_TESTING"
popd

echo "################################################################"
echo "#"
echo "# -----=====>>>>> LFS-user PASS: PHASE COMPLETE <<<<<=====-----"
echo "#"
echo "################################################################"

chown -R root:root $LFS/tools

if [ 0 -eq "$JUST_TESTING" ] ; then
	./6.02-PREP_VIRT_KERNEL_FS
fi
echo "################################################################"
echo "#"
echo "#  [ 6.02 - PREP_VIRT_KERNEL_FS ] run successfully; continuing"
echo "#"
echo "################################################################"
time

cd $LFS/lfs
if [ 0 -eq "$JUST_TESTING" ] ; then
	sed "s,#! /bin/bash,#! /tools/bin/bash," build-all | \
		sed 's,./build ,./build-jail ,' > build-all-jail
	sed "s,#! /bin/bash,#! /tools/bin/bash," build > build-jail
	chmod 0755 *-jail

	# Unpack the BLFS bootscripts for later
	tar xf src/blfs-bootscripts-*.tar.*
fi

chroot "$LFS" /tools/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
	/tools/bin/bash +h /lfs/lfs-06.05-build $JUST_TESTING

echo "################################################################"
echo "#"
echo "# -----=====>>>>> LFS-chroot, 1: PHASE COMPLETE <<<<<=====-----"
echo "#"
echo "################################################################"

chroot "$LFS" /tools/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
        /bin/bash +h /lfs/lfs-06.31-restart-bash $JUST_TESTING

echo "################################################################"
echo "#"
echo "# -----=====>>>>> LFS-chroot, 2: PHASE COMPLETE <<<<<=====-----"
echo "#"
echo "################################################################"

chroot "$LFS" /usr/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
        /bin/bash +h /lfs/lfs-07.02-notools-jail3 $JUST_TESTING

echo "################################################################"
echo "#"
echo "# -----=====>>>>> LFS-chroot, 3: PHASE COMPLETE <<<<<=====-----"
echo "#"
echo "################################################################"

chroot "$LFS" /usr/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
        /bin/bash +h /lfs/lfs-b0-prep-blfs

echo "################################################################"
echo "#"
echo "# -----=====>>>>> BLFS-prep (root): PHASE COMPLETE <<<<<=====-----"
echo "#"
echo "################################################################"

chroot "$LFS" /usr/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin \
        /bin/bash +h /lfs/lfs-b1-build-as-blfs

########################################################################
#
# Wrap up
#
########################################################################
echo
echo "################################################################"
echo "#"
echo "# -----=====>>>>> BLFS-b1 (blfs): PHASE COMPLETE <<<<<=====-----"
echo "#"
echo "################################################################"

########################################################################
#
# Change GRUB to allow us to boot to bare-metal LFS
#
########################################################################
./modify-grub-lfs-p1 -y

echo
echo "################################################################"
echo "#"
echo "#  GRUB1 boot configuration changed; ready for reboot!"
echo "#"
echo "################################################################"


