#! /bin/bash

set +h
set -e
umask 022
PATH=/bin:/usr/bin:/sbin:/usr/sbin
export PATH

export LFS="/"

cd /lfs
find src -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;
chmod a+rw src
pwd
./build-all -s b1.00 -e b1.00

su -c "./build-all -s b1.01 -e b1.07" blfs

./build-all -s b1.08 -e b1.10

su -c "./build-all -s b1.15 -e b1.25" blfs

./build-all -s b1.30 -e b1.30

su -c "./build-all -s b1.31 -e b1.69" blfs

./build-all -s b1.70 -e b1.99

