#! /bin/bash

echo "########################################################################"
echo "#"
echo "#      -----=====> Starting X/LAPP (Phase 2) build... <=====-----"
echo "#"
echo "########################################################################"

if [ ! -e /etc/lfs-release ] ; then
	echo "  This does not look like the X/LAPP install."
	echo "    (No /etc/lfs-release) found; aborting"
	exit 1
fi

echo "  Setting permissions..."
chown -R blfs:blfs /lfs

echo "  Starting build..."
time env -i PATH=/bin:/usr/bin:/sbin:/usr/sbin ./lfs-b2-post-boot

if [ 0 -ne $? ] ; then
echo "########################################################################"
echo "#"
echo "#       -----=====> X/LAPP (Phase 2) build FAILED <=====-----"
echo "#"
echo "########################################################################"
exit 1
else
echo "########################################################################"
echo "#"
echo "#      -----=====> X/LAPP (Phase 2) build successful! <=====-----"
echo "#"
echo "#  * Adjust X/LAPP system to boot Xen Hypervisor/Dom0 kernel."
echo "#"
echo "#  * Xen Hypervisor [ xen-4.1.2.gz ] installed to /boot."
echo "#"
echo "#  * Reboot system after boot-adjustment to run Dom0!"
echo "#"
echo "########################################################################"
fi

