#! /bin/bash
set -e

echo "########################################################################"
echo "#"
echo "#      -----=====> Starting XLAPP (Phase 2) build... <=====-----"
echo "#"
echo "########################################################################"

if [ ! -e /etc/lfs-release ] ; then
	echo "  This does not look like the XLAPP install."
	echo "    (No /etc/lfs-release) found; aborting"
	exit 1
fi

echo "  Setting permissions..."
chown -R blfs:blfs /lfs

echo "  Starting build..."
time env -i PATH=/bin:/usr/bin:/sbin:/usr/sbin ./lfs-b2-post-boot

echo "  Modifying GRUB boot..."
./modify-grub-xlapp-p2 -y

if [ 0 -ne $? ] ; then
echo "########################################################################"
echo "#"
echo "#       -----=====> XLAPP (Phase 2) build FAILED <=====-----"
echo "#"
echo "########################################################################"
exit 1
else
echo "########################################################################"
echo "#"
echo "#      -----=====> XLAPP (Phase 2) build successful! <=====-----"
echo "#"
echo "#  * Adjust XLAPP system to boot Xen Hypervisor/dom0 kernel."
echo "#"
echo "#  * Xen Hypervisor [ xen-4.1.2.gz ] installed to /boot."
echo "#"
echo "#  * Reboot system after boot-adjustment to run dom0!"
echo "#"
echo "########################################################################"
fi

