#! /bin/sh
################################################################
# Begin xlapp-domains
#
# Description : Start Xen Domains
#
# Author      : Qrux - qrux dot qed @ gmail.com
#
# Version     : X/LAPP-0.01
#
################################################################

### BEGIN INIT INFO
# Provides:            xlapp-domains
# Required-Start:      network
# Should-Start:
# Required-Stop:       sendsignals
# Should-Stop:
# Default-Start:       3 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts Xen Domains.
# Description:         Starts Xen Domains.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

XLAPP_COMMAND=/usr/bin/xl
XLAPP_AUTO_DOMAIN_DIR=/etc/xen/auto
XLAPP_RUN_DIR=/var/run/xlapp
XLAPP_SHUTDOWN_TIMEOUT=60

XLAPP_INTERVAL_BETWEEN_DOTS=1

CMD="${1}"

if [ ! -x ${XLAPP_COMMAND} ] ; then
	log_failure_msg "Xen domain-management command [ ${XLAPP_COMMAND} ] missing; aborting"
	exit 1
fi

case "${CMD}" in
start)
	log_info_msg "Starting Xen Domains...\n"
	for _XD in $(echo ${XLAPP_AUTO_DOMAIN_DIR}/*) ; do
		_XDNAME=$(basename ${_XD} | cut -d '.' -f 1)
		log_info_msg "  Starting [ ${_XDNAME} ] DomU ..."
		echo "Starting [ ${_XDNAME} ] DomU from config file [ ${_XD} ]..." > ${XLAPP_RUN_DIR}/start-${_XDNAME}
		${XLAPP_COMMAND} create ${_XD} >> ${XLAPP_RUN_DIR}/start-${_XDNAME} 2>&1
		evaluate_retval
	done
	;;

stop)
	log_info_msg "Stopping Xen Domains...\n"
	_XDLIST="echo $(xl list | egrep -v "^Name[[:space:]]|^Domain-0[[:space:]]" | awk '{print $1}')"
	for _XD in $(${_XDLIST}) ; do
		log_info_msg "  Shutting-down [ ${_XD} ] DomU..."
		${XLAPP_COMMAND} shutdown ${_XD} > ${XLAPP_RUN_DIR}/stop-${_XD} 2>&1
		# Wait 10 seconds, and see if the VM actually stopped...
		_GOOD_SHUTDOWN=1
		for _WAIT in $(seq 1 $((${XLAPP_SHUTDOWN_TIMEOUT} / ${XLAPP_INTERVAL_BETWEEN_DOTS}))) ; do
			${XLAPP_COMMAND} list | awk '{print $1}' | grep -w "${_XD}" > /dev/null
			if [ $? -ne 0 ] ; then
				_GOOD_SHUTDOWN=0
				break
			else
				echo -e -n "."
				sleep ${XLAPP_INTERVAL_BETWEEN_DOTS}
			fi
		done
		test 0 -eq ${_GOOD_SHUTDOWN}
		evaluate_retval
	done
	;;

status)
	${XLAPP_COMMAND} list
	;;

*)
	echo "Usage: $0 {start|stop|status}"
	exit 1
	;;
esac

# End xlapp-domains bootscript
